### PR TITLE
runtests.py: treat strings within quotes as a single string

### PR DESCRIPTION
**Pull request by xupengfe**
Treat strings within quotes as a single string:
It could solve the avx512vbmi/tests like "0 ff b" could not be executed by runtest.py.

### CODE REVIEW

**Comment by ysun** [comment]
Hi @xupengfe , appreciate your quick response. I have another implement for this issue, that is more "python style"
please review:  https://github.com/intel/lkvs/pull/317
Add  @haoliang-Zhu  for more comments, too.

**Comment by xupengfe** [comment]
Hi @ysun ，
I was the first to fix this problem, and according to community guidelines, the maintainer can suggest improvements, but the original fix should be acknowledged. 

Yes, the cmd line should be parsed together, it's better.
Additionally, your submitted patch does not account for exception cases.

I included you as 'Co-developed-by' and Zhu Haoliang as 'Reported-by'. Would you agree with this approach?
Please check the https://github.com/intel/lkvs/pull/318

Thanks!

**Comment by xupengfe** [comment]
Hi @ysun ，
I was the first to fix this problem, and according to community guidelines, the maintainer can suggest improvements, but the original fix should be acknowledged. 

Yes, the cmd line should be parsed together is better.
Additionally, your submitted patch does not account for exception cases. I improved it.
I included you as 'Co-developed-by' and Zhu Haoliang as 'Reported-by'. Would you agree with this approach?
Please check the https://github.com/intel/lkvs/pull/318

Thanks!

**Comment by ysun** [comment]
> Hi @ysun ， I was the first to fix this problem, and according to community guidelines, the maintainer can suggest improvements, but the original fix should be acknowledged.
> 
> Yes, the cmd line should be parsed together is better. Additionally, your submitted patch does not account for exception cases. I improved it. I included you as 'Co-developed-by' and Zhu Haoliang as 'Reported-by'. Would you agree with this approach? Please check the #318
> 
> Thanks!

Sure, thanks Pengfei's professional commonts, and the new commit.  The approach is good to me.
Please close this PR, let's review the #318

**Pull request closed without merging**
