### PR TITLE
Guest test tdx bugfix

### PR DESCRIPTION
**Pull request by hongyuni**
fix a path error in test_executor

### CODE REVIEW

**Comment by hongyuni** [comment]
please Ning and Yi help to review code based on SW arch flow from slides 2 in following link:
https://intel.sharepoint.com/:p:/r/sites/SSPCLKVAL/Shared%20Documents/General/TDX_1.0/[TDX_auto_framework_flow.pptx](https://intel.sharepoint.com/:p:/r/sites/SSPCLKVAL/Shared%20Documents/General/TDX_1.0/TDX_auto_framework_flow.pptx?d=w8bd7cd03e8f34395b01853de4f648505&csf=1&web=1&e=5QTfXT)?d=w8bd7cd03e8f34395b01853de4f648505&csf=1&web=1&e=5QTfXT

**Review by ysun — APPROVED** [review]

**Comment by ysun** [comment]
The patch set looks good to me!
Thanks Hongyu.

**Comment by ysun** [comment]
I'm not pretty sure whether we should care about the coding check
```
    guest-test/guest.test_executor.sh:28 - Double quote to prevent globbing and word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2086
    guest-test/guest.test_executor.sh:34 - Double quote to prevent globbing and word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2086
```
```
    guest-test/guest.test_launcher.sh:76 - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:199 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053
    guest-test/guest.test_launcher.sh:203 - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:274 - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:291 - Check exit code directly with e.g. 'if mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:3[11](https://github.com/intel/lkvs/actions/runs/6335452419/job/17565972141?pr=118#step:4:12) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
```
Ning can give some comments.

**Comment by hongyuni** [comment]
[Hongyu] $1 not double quoted here, is it quite necessary?
    guest-test/guest.test_executor.sh:28 - Double quote to prevent globbing and word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2086
    guest-test/guest.test_executor.sh:34 - Double quote to prevent globbing and word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2086

[Hongyu] use $? to make rest of logic clear reading, if !mycmd may confuse and not easy to maintain in future
    guest-test/guest.test_launcher.sh:76 - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:203 - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:274 - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:291 - Check exit code directly with e.g. 'if mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
    guest-test/guest.test_launcher.sh:3[11](https://github.com/intel/lkvs/actions/runs/6335452419/job/17565972141?pr=118#step:4:12) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181

[Hongyu] this one is tricky and weird, trigged revise it but the logic can't work as expected, so keep it the way right now
    guest-test/guest.test_launcher.sh:199 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053

**Comment by hongyuni** [comment]
Hi @hanning0511 , @ysun 

I've revised based on offline review with Ning, the remained code check failure like following will be ignored temporarily since code change directly will broke the logic unexpectedly.

`guest-test/guest.test_launcher.sh:199 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053` 

please note, there are 5 more code check failure like above brought back to secure the original design logic.

as synced with Ning, will seek solution continuously and try to fix it with no code check failure  + all logic correct.

would you help to review and decide whether code can be merged?

Thanks,
Hongyu

**Comment by ysun** [comment]
> Hi @hanning0511 , @ysun
> 
> I've revised based on offline review with Ning, the remained code check failure like following will be ignored temporarily since code change directly will broke the logic unexpectedly.
> 
> `guest-test/guest.test_launcher.sh:199 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053`
> 
> please note, there are 5 more code check failure like above brought back to secure the original design logic.
> 
> as synced with Ning, will seek solution continuously and try to fix it with no code check failure + all logic correct.
> 
> would you help to review and decide whether code can be merged?
> 
> Thanks, Hongyu

That works for me. I've noticed that you've made a new commit to address the issue. However, it seems that another "merge commit" has been added, which has made the commit history somewhat cluttered. Would it be possible for you to remove that merge commit to keep the history cleaner? 
You can just operate on your tree(run a git rebase), then the PR will be updated automatically.

I'd like merge it today, so long as Ning has no comments.
@hanning0511 Please "approve it" if the patch set looks good to you.

**Review by hanning0511 — APPROVED** [review]

**Comment by ysun** [comment]
Currently, there is only one type of Check that is being ignored. However, we can work on resolving it in the future.

 guest-test/guest.test_launcher.sh:211 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053
    guest-test/guest.test_launcher.sh:216 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053
    guest-test/guest.test_launcher.sh:219 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053
    guest-test/guest.test_launcher.sh:222 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053
    guest-test/guest.test_launcher.sh:225 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053
    guest-test/guest.test_launcher.sh:228 - Quote the right-hand side of == in [[ ]] to prevent glob matching., refer to https://github.com/koalaman/shellcheck/wiki/SC2053

**Pull request merged**
