### PR TITLE
UMIP test: Initial version for UMIP test.

### PR DESCRIPTION
**Pull request by xupengfe**
UMIP(User-Mode Instruction Prevention) is a security feature in Intel Processors. If UMIP is enabled, it verifies that execution of the instructions(SGDT, SIDT, SLDT, SMSW, STR) should return a sinal SEGV(Segmentation Violation) or a dummy value if CPL(Current Privilege Level) is greater than 0.

Below instructions are protected by UMIP feature:
* SGDT - Store Global Descriptor Table
* SIDT - Store Interrupt Descriptor Table
* SLDT - Store Local Descriptor Table
* SMSW - Store Machine Status Word
* STR  - Store Task Register For the detailed information, please check the README.md in umip folder.

Reviewed-by: Yi Sun <yi.sun@intel.com>
Signed-off-by: Pengfei Xu <pengfei.xu@intel.com>

### CODE REVIEW

**Comment by laifryiee** [comment]
Comit message: sinal -> signal

Do all Intel processors support UMIP? Should we specify after which generations that this feature is supported?

**Comment by ysun** [comment]
>  If UMIP is enabled, it verifies that execution of the instructions(SGDT, SIDT, SLDT, SMSW, STR) should return a sinal
SEGV(Segmentation Violation) or a dummy value if CPL(Current Privilege Level) is greater than 0.

1, Besides the typo, could you reword this sentence which is quite confusing.
2, Shall we supplement some usage of the binary in the README ? Such as the parameters and expected output ?

**Comment by xupengfe** [comment]
> Comit message: sinal -> signal
> 
> Do all Intel processors support UMIP? Should we specify after which generations that this feature is supported?

Thanks for remind, It's fixed.

**Comment by xupengfe** [comment]
> > If UMIP is enabled, it verifies that execution of the instructions(SGDT, SIDT, SLDT, SMSW, STR) should return a sinal
> > SEGV(Segmentation Violation) or a dummy value if CPL(Current Privilege Level) is greater than 0.
> 
> 1, Besides the typo, could you reword this sentence which is quite confusing. 2, Shall we supplement some usage of the binary in the README ? Such as the parameters and expected output ?

Thanks, it's fixed.

**Review by laifryiee — APPROVED** [review]

**Review by ysun — APPROVED** [review]

**Pull request merged**
