### PR TITLE
TH test: Initial version for TH test.

### PR DESCRIPTION
**Pull request by ammyyi**
TH test will inculde set/get policy test.

Reviewed-by: Yi Sun <yi.sun@intel.com>
Signed-off-by: ammy.yi@intel.com <ammy.yi@intel.com>

### CODE REVIEW

**Review by ysun — APPROVED** [review]
The code and README are good to me.

**Review by laifryiee — COMMENTED** [review]
Can we add need one small description about how to th_test / cmds? Or we plan to log it in other places?

**Comment by xupengfe** [comment]
Hi @ammyyi,

It's better to add .gitignore file to avoid th_test binary.
Then git status will ignore the th_test binary.

Thanks!

**Comment by ammyyi** [comment]
> Can we add need one small description about how to th_test / cmds? Or we plan to log it in other places?

Added in README.

**Comment by ammyyi** [comment]
> Hi @ammyyi,
> 
> It's better to add .gitignore file to avoid th_test binary. Then git status will ignore the th_test binary.
> 
> Thanks!

Added in latest patch.

**Review by xupengfe — APPROVED** [review]

**Review by laifryiee — APPROVED** [review]
Looks good to me.

**Pull request merged**
